# Generated by Django 5.0.2 on 2024-03-01 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Number', 'Number')], default='Text', max_length=120)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_field_configurations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=1024, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_fields', to='patients.patient')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_fields', to=settings.AUTH_USER_MODEL)),
                ('additional_field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='additional_fields_values', to='patients.additionalfieldconfiguration')),
            ],
        ),
    ]
